[mgr]
tab_width = 1
border_style = { fg = "white" }
cwd = { fg = "white" }

[style]
fg = "white"
bg = "black"

[mode]
normal_main = { bg = "black" }
normal_alt  = { fg = "white", bg = "black" }

[filetype]
rules = [
	{ name = "*/", fg = "white" }
]
