[mgr]
show_hidden = true
ratio = [2, 2, 5]

[preview]
max_width = 1200
max_height = 1800

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true },
]
mpv = [
	{ run = 'mpv --keep-open=yes "$@"', orphan = true },
]
zathura = [
	{ run = 'zathura "$@"', orphan = true },
]

[open]
rules = [ 
  { mime = "video/*", use = "mpv" },
  { mime = "image/*", use = "mpv" },
  { mime = "application/pdf", use = "zathura" },
  { mime = "*", use = "edit" },
]
