format = """$directory$git_branch$git_status
$character"""

[directory]
style = "white"
read_only = " ro"
truncate_to_repo = false
truncation_length = 3

[git_branch]
symbol = " "
style = "white"
format = "[$symbol$branch]($style) "

[git_status]
style = "white"
# format = "[$all_status]($style) "
# ahead = "⇡${count} "
# behind = "⇣${count} "
# diverged = "⇕⇡${ahead_count}⇣${behind_count} "
# conflicted = "!"
# untracked = "?"
# stashed = "$"
# modified = "~"
# staged = "+"
# renamed = "»"
# deleted = "✘"

[character]
success_symbol = "[➜](white)"
error_symbol = "[✗](white)"

